-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 14:07:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rock_paper_scissors
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rock_paper_scissors` ;

-- -----------------------------------------------------
-- Schema rock_paper_scissors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rock_paper_scissors` DEFAULT CHARACTER SET utf8 ;
USE `rock_paper_scissors` ;

-- -----------------------------------------------------
-- Table `rock_paper_scissors`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rock_paper_scissors`.`users` ;

CREATE TABLE IF NOT EXISTS `rock_paper_scissors`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `loses` INT NULL DEFAULT 0,
  `wins` INT NULL DEFAULT 0,
  `draws` INT NULL DEFAULT 0,
  `rounds` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
